// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGMAfTOp7EtC5capY7VAVDdIcxnbjsJrM',
    appId: '1:28718698907:web:8e3e6138f65290cf8ed13e',
    messagingSenderId: '28718698907',
    projectId: 'fruits-hub-1f795',
    authDomain: 'fruits-hub-1f795.firebaseapp.com',
    storageBucket: 'fruits-hub-1f795.firebasestorage.app',
    measurementId: 'G-C0EBG65JPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFi0Eq0KDLzWwcqAeCLYAifpM4isoytgE',
    appId: '1:28718698907:android:0fea3402c483c2f48ed13e',
    messagingSenderId: '28718698907',
    projectId: 'fruits-hub-1f795',
    storageBucket: 'fruits-hub-1f795.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0dLt63sF8Sn2bbiIaMPUlre2HCWh6kQU',
    appId: '1:28718698907:ios:0d70a7e25b77bb438ed13e',
    messagingSenderId: '28718698907',
    projectId: 'fruits-hub-1f795',
    storageBucket: 'fruits-hub-1f795.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0dLt63sF8Sn2bbiIaMPUlre2HCWh6kQU',
    appId: '1:28718698907:ios:0d70a7e25b77bb438ed13e',
    messagingSenderId: '28718698907',
    projectId: 'fruits-hub-1f795',
    storageBucket: 'fruits-hub-1f795.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGMAfTOp7EtC5capY7VAVDdIcxnbjsJrM',
    appId: '1:28718698907:web:fca44bff7125c6b08ed13e',
    messagingSenderId: '28718698907',
    projectId: 'fruits-hub-1f795',
    authDomain: 'fruits-hub-1f795.firebaseapp.com',
    storageBucket: 'fruits-hub-1f795.firebasestorage.app',
    measurementId: 'G-7QVNXJK18K',
  );
}
